'use client'
import { Provider } from 'react-redux'
import store from '../store/store'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1>Ini Navbar</h1>
      <Provider store={store}>
        {children}
      </Provider>
      </body>
    </html>
  )
}
